### ISSUE TITLE
Trellis support on AWS using Docker

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_server#3]

**Comment by atz** [comment]
I'm interpreting this as "build a docker image containing trellis" and "run that image in AWS".

**Comment by atz** [comment]
Except that Trellis already has docker images aplenty:
https://hub.docker.com/search/?isAutomated=0&isOfficial=0&page=1&pullCount=0&q=trellisldp&starCount=0

So the question is more "can we run it in AWS?"

**Comment by cmh2166** [comment]
yep; in particular, what does that mean for:
1. user configuration if we remain with basic auth which trellis runs via a config file (despite security concerns)
2. connecting the trellis codebase to a RDS instance running as postgres
3. connecting the trellis codebase's expected file mounts to something like S3 (see the logs, mememto, and data set up in trellis `config`)

**Comment by jermnelson** [comment]
Closing
