### ISSUE TITLE
Write resourceTemplates to AWS Trellis via API

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_server#38]
ultimately, would like entire starter set of resourceTemplates in prod AWS sinopia server

obviously, start with a handful of templates to AWS dev.

Putting this here so it's handy:  https://github.com/LD4P/sinopia_server/wiki/Draft-Notes-for-Sinopia-Server-API-Spec

**Comment by ndushay** [comment]
On my laptop, spun up sinopia_server with docker-compose and was able to:
- using trellis built in user file (etc/users.auth)
- curl to create groups
- curl web acl permissions for user/groups
- curl resourceTemplate JSON to local trellis instance via API
    - Slug ok with colons, e.g.  http://localhost:8080/ndushay/sinopia:resourceTemplate:bf2:EditionInformation as an end url

**Comment by ndushay** [comment]
Before Cognito hookup, we need dev AWS trellis to know about a few users for testing.

**Comment by jmartin-sul** [comment]
i think it'd be good to start using the `sinopia_client` SDK to do this.  even if the method calls as they are don't do what we want, we'll need to figure out the needed swagger spec adjustments to get them to do what we want.  and we already know how to use curl for this (though in a pinch, if resource templates on trellis would be helpful for unblocking other work, curl would be fine).
