### ISSUE TITLE
trellis-ext-db doesn't seem to return @type on base resource

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_server#44]
we send @type as `['ldp:Container', 'ldp:BasicContainer']`, and for a while it seemed like i got that back in my tests, but now i don't, whether running locally on my laptop, or in circleci.

**Comment by acoburn** [comment]
In Trellis, LDP types can only be set and retrieved via link headers. They will never be in the response of a GET request.

**Comment by jmartin-sul** [comment]
@acoburn, good to know, thanks!

**Comment by jermnelson** [comment]
Hi @jmartin-sul, should this issue be closed?
