### ISSUE TITLE
trellis seems to allow container creation for a few minutes after ACL update - i.e., there seems to be an authorization application delay. Can we repair this?

### ISSUE THREAD

**Issue by cmh2166** [LD4P/sinopia_server#5]

**Comment by acoburn** [comment]
The auth service has a caching mechanism (for performance reasons). The default is set to 600 seconds per resource, but this can be altered in the config.yml file under auth / webac/ cacheExpireSeconds.

Feel free to open an issue in the trellis repo to remind me to document this. (It is not presently documented)

**Comment by cmh2166** [comment]
thanks @acoburn for this! makes sense. and will open docs issue.
