### ISSUE TITLE
design "Upload Profile" tab

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_server#53]
how will profile creators add their new or revised profiles to the Sinopia server so that those profiles can be used for cataloging?

we decided a separate tab for uploading profiles will be the cleanest way

please design tab to handle use cases in this diagram:
https://docs.google.com/drawings/d/1L6LcQojGtFE40o4e5chLQCgCfBkl7Pbhp006ytnsqS8/

NOTE: we are not making any distinctions at this point between profiles and resource templates. just consider a profile to be a generic form configuration, a file that is created in the Profile Editor, and later uploaded to Sinopia using this new tab

this tab will be implemented for Milestone 3

**Comment by astridu** [comment]
Here is a prototype of the proposed behavior. The first 4 screens show the 'happy' path where all goes well. The next 3 screens show some examples of how to handle errors. https://invis.io/WDQFD026J9F#/345867056_Profiles_Home
Happy to discuss if you want to go over it.

**Comment by michelleif** [comment]
nice! I couldn't advance to the 3 error handling screens


________________________________

**Comment by astridu** [comment]
After the 4th screen, click on the right arrow to see the next 3 screens. Or click on the small icon on the bottom that looks like little boxes stacked together, and you'll see all the screens in the prototype.

**Comment by astridu** [comment]
I've updated the screens: https://invis.io/WDQFD026J9F
I also included a screenshot of what the profile search might look like in the Editor tab if it's decided that's needed.

**Comment by michelleif** [comment]
shared designs with Profiles Working Group co-chairs, asked them to get feedback from the WG
