### ISSUE TITLE
make sure we've spec'ed getResource properly

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_server#56]
make sure the `getResource` method from the `sinopia_client` SDK behaves as desired, since this will likely be the thing the now-in-progress indexing daemon uses to ask trellis for the content it will be indexing (#55).

**Comment by jmartin-sul** [comment]
we have a test for non-RDF resources, just need to make sure we have this for RDF resources.

turns out the indexing pipeline doesn't need this for now (may later), but the editor will.

for RDF resources, this may involve making sure the return type for the operation has a structure that matches what we might get back from trellis, so that we can try to use `getResource` to parse the response automatically.

if getting that return type right is a total pain, we can prob just use `getResourceWithHttpInfo` and use the JSON we get back in the `responseAndData.response.body` field and call it a day.

**Comment by ndushay** [comment]
@jmartin-sul should this issue be M4?

**Comment by jmartin-sul** [comment]
@ndushay, that sounds reasonable to me

**Comment by ndushay** [comment]
@jermnelson wanna make this M4?

**Comment by jermnelson** [comment]
@jmartin-sul and @ndushay  are there specific tests that are needed to close this issue for M4? Otherwise, can we consider changing the label to *debt* and add to work-cycle 2 project? Thanks!

**Comment by jmartin-sul** [comment]
turns out this is done!

https://github.com/LD4P/sinopia_server/commit/195cd17b67181d1793e390f7ddad778d587e43d4#diff-9c98b1f96912899c02b40c5bb91a07dcR269

closing...
