### ISSUE TITLE
deploy updated ld4p/trellis-ext-db docker image, apply terraform changes that give it cognito env vars

### ISSUE THREAD

**Issue by jmartin-sul** [LD4P/sinopia_server#88]
now that we've merged the terraform PR that gives our trellis-ext-db docker container the env vars it needs to do cognito stuff, and now that a docker image that can utilize that config has been pushed to dockerhub, we should:
- [ ] apply the terraform changes
- [ ] deploy the updated image

**Comment by mjgiarlo** [comment]
I believe this is a @rsmith11 issue.

**Comment by jmartin-sul** [comment]
from a cognito perspective, i think this might be done?  @rsmith11?

happy to leave open if we want to make this a more general ticket about successful `ld4p/trellis-ext-db` deployment, since there are still some ActiveMQ config issues being ironed out.  @mjgiarlo, is that work already captured elsewhere?

**Comment by rsmith11** [comment]
The ld4p/trellis-ext-db docker image is running in all environments; DEV,STAGE,PROD.

**Comment by jmartin-sul** [comment]
closing this per @rsmith11's comment just now, happy to reopen if that's incorrect
