### ISSUE TITLE
Change swagger spec for updating a plain json resource and regen api code

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_server#94]
Swagger spec should allow the generated `updateResourceWithHttpInfo()` method to accept `contentType: 'application/json'` (similar to `createResourceWithHttpInfo()`)

**Comment by jgreben** [comment]
Probably should also do `deleteResourceWithHttpInfo()` while you are at it. They are probably going to want a way to delete resources at some point in the near future, even if it's not in this workcycle...

**Comment by mjgiarlo** [comment]
Unassigning because not in progress yet.

**Comment by mjgiarlo** [comment]
@jgreben :speech_balloon: 
> Probably should also do `deleteResourceWithHttpInfo()` while you are at it. They are probably going to want a way to delete resources at some point in the near future, even if it's not in this workcycle...

As I understand it, the delete resource request does not include a request body, so passing a content-type header wouldn't get us anything (because there is no content type).

**Comment by jmartin-sul** [comment]
> As I understand it, the delete resource request does not include a request body, so passing a content-type header wouldn't get us anything (because there is no content type).

that sounds reasonable to me
